# Generated by Django 2.2 on 2020-09-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainadminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booki',
            old_name='roomno',
            new_name='roomid',
        ),
    ]
