# Generated by Django 2.2 on 2020-09-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainadminapp', '0002_auto_20200910_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booki',
            name='age',
            field=models.CharField(max_length=2),
        ),
    ]
