# Generated by Django 2.2 on 2020-10-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainadminapp', '0003_auto_20200910_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booki',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='booki',
            name='country',
            field=models.CharField(max_length=25),
        ),
    ]
