# Generated by Django 2.2 on 2020-10-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainadminapp', '0005_auto_20201017_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booki',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
