# Generated by Django 2.2 on 2020-10-23 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainadminapp', '0007_auto_20201023_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booki',
            name='agentid',
            field=models.ForeignKey(db_column='agentid', on_delete=django.db.models.deletion.CASCADE, to='mainadminapp.Agent'),
        ),
    ]
