# Generated by Django 2.2 on 2020-10-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainadminapp', '0008_auto_20201023_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booki',
            name='address',
            field=models.CharField(default=0, max_length=70),
        ),
    ]
