# Generated by Django 2.2 on 2020-10-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainadminapp', '0009_auto_20201023_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booki',
            name='noofrooms',
            field=models.IntegerField(default=0),
        ),
    ]
